#include "world.hpp"

#include <cassert>
#include <iostream>
#include <thread>
#include <unordered_set>

const World::ChunkCoord World::chunkCenterToChunkCoord(const ChunkCenter& chunk_center) const
{
    return chunk_center / static_cast<float>(chunkSize);
}

const World::ChunkCenter World::posToChunkCenter(const glm::vec3& pos) const
{
    const float fp_chunk_size = static_cast<float>(chunkSize);
    const float stride = fp_chunk_size;
    const float x = std::floorf(((pos.x + 0.5f) / fp_chunk_size + 0.5f)) * stride;
    const float z = std::floorf(((pos.z + 0.5f) / fp_chunk_size + 0.5f)) * stride;
    return World::ChunkCenter(x, z);
}

World::World(const unsigned seed, const int chunk_size, const glm::vec3& origin, const unsigned radius)
    : noise(seed), seed(seed), chunkSize(chunk_size)
{
    std::cout << ">>> Loading world with seed (" << seed << ")..." << std::endl;

    const unsigned total_num_chunks = updateChunks(origin, radius);

    // Report an update every second.
    do
    {
        std::cout << "  Loaded " << (total_num_chunks - chunksToAdd.size()) << "/" << total_num_chunks << " chunks."
                  << std::endl;
        std::this_thread::sleep_for(std::chrono::seconds(1));
    } while (!chunksToAdd.empty());

    std::cout << "  Loaded " << (total_num_chunks - chunksToAdd.size()) << "/" << total_num_chunks << " chunks."
              << std::endl;

    std::cout << ">>> Finished loading world!" << std::endl;
}

World::~World()
{
    for (auto& chunk : chunks)
    {
        free(chunk.second);
    }
}

std::optional<glm::vec3> World::getReachableBlock(const Ray& ray, glm::ivec3* face_entered)
{
    std::lock_guard<std::mutex> lock(activeChunksMutex);

    std::optional<glm::vec3> reachable_block_pos;

    // Under the assumption that the player's reach is never infinity.

    // Check the chunk that contains the ray's origin (the player's position).
    const ChunkCenter chunk_center = posToChunkCenter(ray.getOrigin());
    ChunkCoord cc = chunkCenterToChunkCoord(chunk_center);
    reachable_block_pos = activeChunks[cc]->getReachableBlock(ray, face_entered);
    if (reachable_block_pos.has_value())
    {
        return reachable_block_pos;
    }

    // Check the chunk that contains the ray's direction at its max distance (where the player is looking).
    const ChunkCenter next_chunk_center = posToChunkCenter(ray.getOrigin() + ray.getDirection() * ray.getMax());
    if (next_chunk_center == chunk_center)
    {
        return reachable_block_pos;
    }
    cc = chunkCenterToChunkCoord(next_chunk_center);
    reachable_block_pos = activeChunks[cc]->getReachableBlock(ray, face_entered);

    return reachable_block_pos;
}

void World::addChunk(const std::vector<glm::vec2> chunk_centers)
{
    for (const auto& chunk_center : chunk_centers)
    {
        const ChunkCoord cc = chunkCenterToChunkCoord(chunk_center);

        // Don't generate the chunk if it was already generated by another thread.
        if (chunks.contains(cc))
        {
            continue;
        }

        noise = FastNoiseLite(seed); // Reset the noise by creating a fresh generator.
        noise.SetNoiseType(FastNoiseLite::NoiseType_OpenSimplex2S);
        noise.SetFractalType(FastNoiseLite::FractalType_FBm);
        noise.SetFractalOctaves(5);
        noise.SetFractalWeightedStrength(1.5f);
        Chunk* chunk = new Chunk{noise, chunk_center, chunkSize};

        {
            std::lock_guard<std::mutex> lock(activeChunksMutex);
            chunks.emplace(cc, chunk);
            activeChunks.emplace(cc, chunks[cc]);
            chunksToAdd.erase(cc);
        }
    }
}

unsigned World::updateChunks(const glm::vec3& origin, const unsigned radius)
{
    // TODO: change to update in 3D.
    // Load all chunks visible to the player.
    const int render_distance = static_cast<int>(radius);
    const float offset = static_cast<float>(render_distance * chunkSize);

    std::unordered_set<ChunkCoord> inactive_chunks;
    for (const auto& entry : activeChunks)
    {
        inactive_chunks.emplace(entry.first);
    }

    std::vector<glm::vec2> chunk_centers;
    bool add_chunks = false;

    float x = origin.x - offset;
    for (int i = 0; i <= (render_distance * 2); ++i)
    {
        float z = origin.z - offset;
        for (int j = 0; j <= (render_distance * 2); ++j)
        {
            const ChunkCenter chunk_center = posToChunkCenter({x, 0.0f, z});
            const ChunkCoord cc = chunkCenterToChunkCoord(chunk_center);
            inactive_chunks.erase(cc);
            if (!activeChunks.contains(cc))
            {
                if (!chunks.contains(cc))
                {
                    // Create the chunk asynchrounously and add it later.
                    if (!chunksToAdd.contains(cc))
                    {
                        chunksToAdd.emplace(cc);
                        chunk_centers.emplace_back(chunk_center);
                        add_chunks = true;
                    }
                }
                else
                {
                    activeChunks.emplace(cc, chunks[cc]);
                }
            }
            z += chunkSize;
        }
        x += chunkSize;
    }

    if (add_chunks)
    {
        // Give a batch of chunks to a single async thread to process.
        // TODO: use thread pool to avoid overhead.
        std::thread(&World::addChunk, this, chunk_centers).detach();
    }

    {
        std::lock_guard<std::mutex> lock(activeChunksMutex);

        // Remove now inactive chunks.
        for (const auto& cc : inactive_chunks)
        {
            activeChunks.erase(cc);
        }
    }

    return static_cast<unsigned>(chunk_centers.size());
}

void World::addBlock(const glm::vec3 block_pos)
{
    std::vector<glm::vec3> offsets = {
        glm::vec3(0.0f, 0.0f, 0.0f),
        glm::vec3(1.0f, 0.0f, 0.0f),
        glm::vec3(-1.0f, 0.0f, 0.0f),
        glm::vec3(0.0f, 0.0f, 1.0f),
        glm::vec3(0.0f, 0.0f, -1.0f),
    };
    for (const auto& offset : offsets)
    {
        const ChunkCenter chunk_center = posToChunkCenter(block_pos + offset);
        ChunkCoord cc = chunkCenterToChunkCoord(chunk_center);
        activeChunks[cc]->addBlock(block_pos);
    }
}

void World::removeBlock(const glm::vec3 block_pos)
{
    std::vector<glm::vec3> offsets = {
        glm::vec3(0.0f, 0.0f, 0.0f),
        glm::vec3(1.0f, 0.0f, 0.0f),
        glm::vec3(-1.0f, 0.0f, 0.0f),
        glm::vec3(0.0f, 0.0f, 1.0f),
        glm::vec3(0.0f, 0.0f, -1.0f),
    };
    for (const auto& offset : offsets)
    {
        const ChunkCenter chunk_center = posToChunkCenter(block_pos + offset);
        ChunkCoord cc = chunkCenterToChunkCoord(chunk_center);
        activeChunks[cc]->removeBlock(block_pos);
    }
}

const std::vector<Chunk*> World::getActiveChunks() const
{
    std::vector<Chunk*> chunks;
    chunks.reserve(activeChunks.size());
    for (const auto& chunk : activeChunks)
    {
        chunks.push_back(chunk.second);
    }
    return chunks;
}

const Model World::getModel() const
{
    std::vector<Model::Vertex> vertices;
    std::vector<Model::Index> indices;
    size_t vertices_size = 0;
    size_t indices_size = 0;
    for (const auto& chunk_info : activeChunks)
    {
        vertices_size += chunk_info.second->getVertices().size();
        indices_size += chunk_info.second->getIndices().size();
    }
    vertices.reserve(vertices_size);
    indices.reserve(indices_size);
    size_t accum = 0;
    for (const auto& chunk_info : activeChunks)
    {
        const auto chunk_vertices = chunk_info.second->getVertices();
        vertices.insert(vertices.end(), chunk_vertices.begin(), chunk_vertices.end());

        auto chunk_indices = chunk_info.second->getIndices();
        for (auto& chunk_index : chunk_indices)
        {
            chunk_index += accum;
        }
        indices.insert(indices.end(), chunk_indices.begin(), chunk_indices.end());
        accum += chunk_vertices.size();
    }

    return Model(vertices, indices);
}
